spring:
  application:
    name: Abac protected API
server:
  servlet:
    context-path: /sample-issue-tracker
    
security:
  abac:
    policy-files:
      - /abac/security/policy/json/default-policy.json
